"""Stable, versioned contracts for cross-module communication."""

from .models import (
    ApprovalRecord,
    ArtifactClassification,
    ArtifactEnvelope,
    DataCompleteness,
    ErrorEnvelope,
    IdempotencyKey,
    NoOp,
    Plan,
    PlanStep,
    QualityAssertion,
    SourceManifest,
    SourceManifestEntry,
    SourceReadiness,
    TraceEvent,
    TraceEventType,
)
from .ports import ArtifactStorePort, ConfigMigration, ConfigPort, RunStateStorePort
from .redaction import (
    REDACTED,
    redact,
    redact_serializable,
    redact_text,
    safe_exception,
    safe_repr,
)
from .schema import contract_schema_bundle
from .state import (
    BranchSnapshot,
    BranchStatus,
    InvalidRunTransition,
    ReportTier,
    RunSnapshot,
    RunStatus,
    transition_branch,
    transition_run,
)

__all__ = [
    "REDACTED",
    "ApprovalRecord",
    "ArtifactClassification",
    "ArtifactEnvelope",
    "ArtifactStorePort",
    "BranchSnapshot",
    "BranchStatus",
    "ConfigMigration",
    "ConfigPort",
    "DataCompleteness",
    "ErrorEnvelope",
    "IdempotencyKey",
    "InvalidRunTransition",
    "NoOp",
    "Plan",
    "PlanStep",
    "QualityAssertion",
    "ReportTier",
    "RunSnapshot",
    "RunStateStorePort",
    "RunStatus",
    "SourceManifest",
    "SourceManifestEntry",
    "SourceReadiness",
    "TraceEvent",
    "TraceEventType",
    "contract_schema_bundle",
    "redact",
    "redact_serializable",
    "redact_text",
    "safe_exception",
    "safe_repr",
    "transition_branch",
    "transition_run",
]
